# fly.toml app configuration file generated for hello-sir on 2023-07-26T17:03:24+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "hello-sir"
primary_region = "cdg"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 1
